workflows:
  android-workflow:
    name: Android Workflow
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter packages get
      - name: Build App Bundle
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
